<?php

/**
 * @file
 * Provided form text element Site API key to the Site Information Form
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for system_site_information_settings form
 */
function siteapi_form_system_site_information_settings_alter(&$form, FormStateInterface &$form_state) {
  $config = \Drupal::config('system.site');
  $form['site_information']['siteapikey'] = [
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#default_value' => $config->get('siteapikey'),
    '#required' => FALSE,
  ];
  $form['site_information']['siteapikey']['#attributes']['placeholder'] = 'No API Key yet';
  $form['actions']['submit']['#value'] = t('Update Configuration');
  $form['#submit'][] = 'siteapi_form_system_site_information_settings_submit';
}

/**
 * Submit Handler for system_site_information_settings form
 */
function siteapi_form_system_site_information_settings_submit(array &$form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('system.site');
  $config->set('siteapikey', $form_state->getValue('siteapikey'))->save();
  drupal_set_message(t('Site API Key has been saved with value @value', array('@value' => $form_state->getValue('siteapikey'))));
}
